name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Unit Tests
        run: ./gradlew test

      - name: Lint
        run: ./gradlew lint

      - name: Assemble Debug
        run: ./gradlew assembleDebug
